# Generated by Django 3.0.4 on 2020-03-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.BinaryField()),
                ('mood', models.TextField(max_length=10)),
            ],
        ),
    ]
