# Generated by Django 3.0.4 on 2020-03-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='name',
            field=models.TextField(default='Test', max_length=50),
        ),
        migrations.AlterField(
            model_name='sound',
            name='location',
            field=models.BinaryField(editable=True),
        ),
    ]
