# Generated by Django 3.0.4 on 2020-03-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0002_auto_20200314_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='location',
            field=models.TextField(default='Test', max_length=50),
        ),
    ]
