# Generated by Django 3.0.4 on 2020-03-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0003_auto_20200314_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='location',
        ),
        migrations.AddField(
            model_name='sound',
            name='filename',
            field=models.TextField(default='Enter Filename', max_length=50),
        ),
        migrations.AddField(
            model_name='sound',
            name='url',
            field=models.TextField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sound',
            name='mood',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sound',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
