# Generated by Django 3.0.4 on 2020-03-14 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0004_auto_20200314_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='filename',
        ),
    ]
