# Generated by Django 3.0.4 on 2020-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundboard', '0005_remove_sound_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sound',
            name='mood',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sound',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sound',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
